- name: setup template
  ansible.builtin.template:
    src: pipeline.xml
    des: /tmp/pipeline.xml

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline.xml') }}"
    name: sample1
    password: sam123
    url: http://172.31.83.34:8080
    user: sam